"""add_deleted_at_column_to_all_tables

Revision ID: 657c93668050
Revises: 92b9dbe1a9cd
Create Date: 2026-01-24 15:48:20.436633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657c93668050'
down_revision: Union[str, None] = '92b9dbe1a9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('statements', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('transactions', 'deleted_at')
    op.drop_column('statements', 'deleted_at')
    op.drop_column('cards', 'deleted_at')
    # ### end Alembic commands ###
