"""Initial schema with users, cards, statements, transactions

Revision ID: a5806189b8bb
Revises: 
Create Date: 2026-01-22 23:35:28.098549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5806189b8bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_bank_code'), 'cards', ['bank_code'], unique=False)
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_table('statements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('statement_month', sa.Date(), nullable=False),
    sa.Column('closing_balance', sa.BigInteger(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'statement_month', name='uq_card_statement_month')
    )
    op.create_index(op.f('ix_statements_card_id'), 'statements', ['card_id'], unique=False)
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('statement_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('is_credit', sa.Boolean(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_transactions_txn_date'), 'transactions', ['txn_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_txn_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_card_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_bank_code'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
